### PR TITLE
use a stack to handle styles inside other styles

### PR DESCRIPTION
**Pull request by zmughal**
There could probably be a better way to handle this, but it will require
more thought.

### CODE REVIEW

**Comment by zmughal** [comment]
By the way, thank you for this module!

It fits my [use case](https://github.com/zmughal/p5-Devel-IPerl/issues/28#issuecomment-73849008) very well and works better than using Pandoc. :-D

**Comment by zmughal** [comment]
@keedi, what do you think of this? Also, #5 will need to be added before a new release is possible.

**Comment by keedi** [comment]
IMHO, although this is not same as original Markdown does, but I like it! But I think it will be better if we could trun on/off this feature when generating the instance.

Thanks again for great work. :-)

**Comment by keedi** [comment]
I've just released [0.006 version](https://metacpan.org/release/KEEDI/Markdown-Pod-0.006). Thanks again. :)

**Pull request merged**
